name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd ~/fullstack-react-node-postgreSQL
            git pull origin main
            cd backend
            sudo docker build -t fullstack-backend:latest .
            sudo docker stop fullstack-backend || true
            sudo docker rm fullstack-backend || true
            sudo docker run -d --name fullstack-backend --restart=always \
              -p 5050:5050 \
              fullstack-backend:latest
            echo "Backend deployed successfully"
