name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd ~/fullstack-react-node-postgreSQL
            git pull origin main
            cd frontend
            sudo docker build -t fullstack-frontend:latest .
            sudo docker stop fullstack-frontend || true
            sudo docker rm fullstack-frontend || true
            sudo docker run -d --name fullstack-frontend --restart=always \
              -p 3000:3000 \
              fullstack-frontend:latest
            echo "Frontend deployed successfully"

